name: SDS Azure Platform
trigger:
  batch: true
  branches:
    include:
      - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/DTSPO-9054/spike_02_jest
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts (1)'

parameters:
  - name: components
    displayName: Component to Run
    type: object
    default:
      - deployment: "backendappgateway"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "dev"
        dependsOn: "sbox_backendappgateway"
      - deployment: "backendappgateway"
        environment: "stg"
        dependsOn: "sbox_backendappgateway"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "demo"
        dependsOn: "sbox_backendappgateway"
      - deployment: "backendappgateway"
        environment: "ithc"
        dependsOn: "sbox_backendappgateway"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "test"
        dependsOn: "sbox_backendappgateway"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "prod"
        dependsOn: "sbox_backendappgateway"
      - deployment: "appgateway"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "dev"
        dependsOn: "sbox_appgateway"
      - deployment: "appgateway"
        environment: "stg"
        dependsOn: "sbox_appgateway"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "demo"
        dependsOn: "sbox_appgateway"
      - deployment: "appgateway"
        environment: "ithc"
        dependsOn: "sbox_appgateway"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "test"
        dependsOn: "sbox_appgateway"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "prod"
        dependsOn: "sbox_appgateway"
      - deployment: "trafficmanager"
        environment: "dev"
        dependsOn: "Precheck"
      - deployment: "trafficmanager"
        environment: "prod"
        dependsOn: "dev_trafficmanager"
      - deployment: "shutter"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "shutter"
        environment: "prod"
        dependsOn: "sbox_shutter"
      - deployment: "apim"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "apim"
        environment: "dev"
        dependsOn: "sbox_apim"
      - deployment: "apim"
        environment: "stg"
        dependsOn: "sbox_apim"
        pipeline_tests: true
      - deployment: "apim"
        environment: "prod"
        dependsOn: "sbox_apim"
      - deployment: "apim"
        environment: "test"
        dependsOn: "sbox_apim"
        pipeline_tests: true
      - deployment: "apim"
        environment: "demo"
        dependsOn: "sbox_apim"
      - deployment: "apim"
        environment: "ithc"
        dependsOn: "sbox_apim"
        pipeline_tests: true
        
  - name: location
    displayName: Location
    type: string
    default: "UK South"
    values:
      - "UK South"
      - "UK West"

variables:
  - name: tfversion
    value: 1.0.4
  - name: project
    value: application
  - name: timeoutInMinutes
    value: "60"
  - name: agentPool
    value: "ubuntu-18.04"
  - name: vmImage
    value: 'ubuntu-latest'
  - name: build
    value: $(Build.BuildNumber)
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: product
    value: "sds-platform"
  - name: tfInitSub
    value: "04d27a32-7a07-48b3-95b8-3c8691e1a263"
  - name: appName
    value: toffee

stages:
  - stage: Precheck
    jobs:
      - job: Validate
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - task: TerraformInstaller@0
            displayName: Terraform install
            inputs:
              terraformVersion: ${{ variables.tfversion }}
          - task: AzureKeyVault@1
            displayName: Retrieve keyvault secret for ADO token
            inputs:
              ConnectedServiceName: DCD-CFT-Sandbox
              keyVaultName: infra-vault-sandbox
              secretsFilter: "azure-devops-token"
              runAsPreJob: false

          - task: Bash@3
            displayName: Prevent parallel run
            env:
              thisbuild: $(Build.BuildId)
              pipelinedefinition: $(System.DefinitionId)
              azuredevopstoken: $(azure-devops-token)
            inputs:
              filePath: pipeline-scripts/builds-check.sh
          - task: PowerShell@2
            displayName: Run tests
            inputs:
              targetType: "filePath"
              filePath: $(System.DefaultWorkingDirectory)/pipeline-scripts/pester-tests.ps1
              pwsh: true
          - task: PublishTestResults@2
            displayName: "Publish Test Results **/TEST-*.xml"
            inputs:
              testResultsFormat: NUnit
              failTaskOnFailedTests: true
            condition: always()

  - ${{ each deployment in parameters.components }}:
      - stage: ${{ deployment.environment }}_${{ deployment.deployment }}
        displayName: ${{ deployment.environment }}_${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job:
            pool:
              vmImage: ${{ variables.agentPool }}
            steps:
              - template: pipeline-templates/terraform.yaml
                parameters:
                  environment: ${{ deployment.environment }}
                  location: ${{ parameters.location }}
                  stack: ${{ deployment.deployment }}
                  project: $(project)
                  tfversion: $(tfversion)
                  serviceConnection: "OPS-APPROVAL-GATE-${{ upper(deployment.environment) }}-ENVS"
                  product: $(product)
                  tfInitSub: ${{ variables.tfInitSub }}
          - ${{ if eq(deployment.pipeline_tests, true) }}:
            - job: PipelineTests
              pool:
                vmImage: ${{ variables.vmImage }}
              timeoutInMinutes: ${{ variables.timeoutInMinutes }}
              steps:
                - template: steps/pipeline-tests-jest.yaml@cnp-azuredevops-libraries
                  parameters:
                    workingDirectory: $(Pipeline.Workspace)/s/sds-azure-platform/scripts
                    junit_output_dir: $(Pipeline.Workspace)/s/sds-azure-platform/environments/${{ deployment.environment }}/junit
                    environment: ${{ deployment.environment }}
                    product: ${{ variables.product }}
                    test_title: '${{ deployment.environment }}_${{ deployment.component }}'
