name: "${{ parameters.action }} - ${{ parameters.location }} - SDS Azure Platform"
trigger:
  batch: true
  branches:
    include:
      - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master/msl8r-patch-1
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts (1)'

parameters:
  - name: action
    displayName: Action
    type: string
    default: 'plan'
    values:
      - plan
      - apply

  - name: location
    displayName: Location
    type: string
    default: "UK South"
    values:
      - "UK South"
      - "UK West"

  - name: components
    displayName: Component to Run
    type: object
    default:
      - deployment: "backendappgateway"
        environment: 'sbox'
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "dev"
        dependsOn: "sbox_backendappgateway"
      - deployment: "backendappgateway"
        environment: "stg"
        dependsOn: "sbox_backendappgateway"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "demo"
        dependsOn: "sbox_backendappgateway"
      - deployment: "backendappgateway"
        environment: "ithc"
        dependsOn: "sbox_backendappgateway"
        pipeline_tests: true
      - deployment: "backendappgateway"
        environment: "test"
        dependsOn: "sbox_backendappgateway"
      - deployment: "backendappgateway"
        environment: "prod"
        dependsOn: "sbox_backendappgateway"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "dev"
        dependsOn: "sbox_appgateway"
      - deployment: "appgateway"
        environment: "stg"
        dependsOn: "sbox_appgateway"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "demo"
        dependsOn: "sbox_appgateway"
      - deployment: "appgateway"
        environment: "ithc"
        dependsOn: "sbox_appgateway"
        pipeline_tests: true
      - deployment: "appgateway"
        environment: "test"
        dependsOn: "sbox_appgateway"
      - deployment: "appgateway"
        environment: "prod"
        dependsOn: "sbox_appgateway"
        pipeline_tests: true
      - deployment: "trafficmanager"
        environment: "dev"
        dependsOn: "Precheck"
      - deployment: "trafficmanager"
        environment: "prod"
        dependsOn: "dev_trafficmanager"
        pipeline_tests: true
      - deployment: "shutter"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "shutter"
        environment: "prod"
        dependsOn: "sbox_shutter"
      - deployment: "apim"
        environment: "sbox"
        dependsOn: "Precheck"
        pipeline_tests: true
      - deployment: "apim"
        environment: "dev"
        dependsOn: "sbox_apim"
      - deployment: "apim"
        environment: "stg"
        dependsOn: "sbox_apim"
        pipeline_tests: true
      - deployment: "apim"
        environment: "prod"
        dependsOn: "sbox_apim"
        pipeline_tests: true
      - deployment: "apim"
        environment: "test"
        dependsOn: "sbox_apim"
        pipeline_tests: true
      - deployment: "apim"
        environment: "demo"
        dependsOn: "sbox_apim"
        pipeline_tests: true
      - deployment: "apim"
        environment: "ithc"
        dependsOn: "sbox_apim"
        pipeline_tests: true

variables:
  - name: project
    value: application
  - name: agentPool
    value: 'ubuntu-latest'
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: "sds-platform"
  - name: tfInitSub
    value: "04d27a32-7a07-48b3-95b8-3c8691e1a263"
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job: Validate
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFTAPPS-STG'
              overrideAction: ${{ parameters.action }}

  - ${{ each parameter in parameters.components }}:
      - stage: ${{ parameter.environment }}_${{ parameter.deployment }}
        displayName: ${{ parameter.environment }}_${{ parameter.deployment }}
        dependsOn: ${{ parameter.dependsOn }}
        jobs:
          - job: TerraformPlanApply
            pool:
              vmImage: ${{ variables.agentPool }}
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.action }}
                  environment: ${{ parameter.environment }}
                  location: ${{ parameters.location }}
                  component: ${{ parameter.deployment }}
                  serviceConnection: "OPS-APPROVAL-GATE-${{ upper(parameter.environment) }}-ENVS"
                  product: $(product)
                  terraformInitSubscription: ${{ variables.tfInitSub }}
                  planCommandOptions: >
                    -var environment=${{ parameter.environment }}
                    -var project=$(project)
          - ${{ if eq(parameter.pipeline_tests, true) }}:
            - job: PipelineTests
              pool:
                vmImage: ${{ variables.agentPool }}
              dependsOn: TerraformPlanApply
              steps:
                - template: steps/pipeline-tests-jest.yaml@cnp-azuredevops-libraries
                  parameters:
                    workingDirectory: $(Pipeline.Workspace)/s/sds-azure-platform/scripts
                    junit_output_dir: $(Pipeline.Workspace)/s/sds-azure-platform/environments/${{ parameter.environment }}/junit
                    environment: ${{ parameter.environment }}
                    product: ${{ variables.product }}
                    test_title: '${{ parameter.environment }}_${{ parameter.deployment }}'
                    ${{ if eq(parameter.deployment, 'apim') }}:
                      test_pattern: apim.test.ts
                    ${{ else }}:
                      test_pattern: pipeline.test.ts
