name: SDS Azure Platform
trigger:
  - none

parameters:
  - name: components
    displayName: Component to Run
    type: object
    default:
      - deployment: 'frontdoor'
        environment: 'ithc'
        dependsOn: 'Precheck'
      - deployment: 'frontdoor'
        environment: 'dev'
        dependsOn: 'Precheck'
      - deployment: 'frontdoor'
        environment: 'demo'
        dependsOn: 'Precheck'
      - deployment: 'frontdoor'
        environment: 'sbox'
        dependsOn: 'Precheck'
      - deployment: 'frontdoor'
        environment: 'stg'
        dependsOn: 'Precheck'
      - deployment: 'frontdoor'
        environment: 'test'
        dependsOn: 'Precheck'
      - deployment: 'frontdoor'
        environment: 'prod'
        dependsOn: 'Precheck'

  - name: location
    displayName: Location
    type: string
    default: 'UK South'
    values:
      - 'UK South'
      - 'UK West'

variables:
  - name: tfversion
    value: 0.14.3
  - name: project
    value: application
  - name: timeoutInMinutes
    value: '60'
  - name: agentPool
    value: 'ubuntu-18.04'
  - name: build
    value: $(Build.BuildNumber)
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]


stages:

  - ${{ each parameter in parameters.components }}:
      - stage: ${{ parameter.environment }}_${{ parameter.deployment }}
        displayName: ${{ parameter.environment }}_${{ parameter.deployment }}
        jobs:
          - job:
            pool:
              vmImage: 'ubuntu-16.04'
            steps:
              - template: pipeline-templates/terraform.yaml
                parameters:
                  environment: ${{ parameter.environment }}
                  location: ${{ parameters.location }}
                  stack: ${{ parameter.deployment }}
                  project: $(project)
                  tfversion: $(tfversion)
                  serviceConnection: OPS-APPROVAL-GATE-upper(${{ parameter.environment }})-ENVS