name: HMCTS Shared Services AKS Azure Infrastructure Component Deployment Pipeline
trigger:
  - none

parameters:
  - name: components
    displayName: Component to Run
    type: object
    default:
      - frontdoor
      - appgateway
  - name: location
    displayName: Location
    type: string
    default: 'UK South'
    values:
      - 'UK South'
      - 'UK West'
  - name: env
    displayName: Environment
    type: string
    default: 'SBOX'
    values:
      - ITHC
      - DEV
      - DEMO
      - SBOX
      - TEST
      - STG
      - PROD


variables:
  - name: tfversion
    value: 0.14.3
  - name: project
    value: application
  - name: serviceConnection
    value: OPS-APPROVAL-GATE-${{ parameters.env }}-ENVS


stages:
  - ${{ each parameter in parameters.components }}:
      - stage: ${{ parameter }}
        displayName: ${{ parameter }}
        jobs:
          - job:
            steps:
              - template: pipeline-templates/terraform.yaml
                parameters:
                  environment: ${{ parameters.env }}
                  location: ${{ parameters.location }}
                  stack: ${{ parameter }}
                  project: $(project)
                  tfversion: $(tfversion)
                  serviceConnection: $(serviceConnection)


