---

gateways:
  - gateway_configuration:
      host_name_suffix: staging.platform.hmcts.net
      ssl_host_name_suffix: staging.platform.hmcts.net
      certificate_name: wildcard-staging-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.148.32.138
    app_configuration:
    # Toffee
      - product: toffee
        component: recipe-backend
    # VH
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-web
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: service-web
        ssl_enabled: true
      - product: vh
        component: scheduler-jobs
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: booking-queue-subscriber
        ssl_enabled: true
      - product: vh
        component: admin-web
        ssl_enabled: true
      - product: vh
        component: test-web
        ssl_enabled: true
      - product: pip
        component: pip-business-rules
        ssl_enabled: true
      - product: pip
        component: pip-publication-services
        ssl_enabled: true
      - product: pip
        component: pip-data-management
        ssl_enabled: true
      - product: pip
        component: pip-channel-management
        ssl_enabled: true
      - product: pip
        component: pip-subscription-management
        ssl_enabled: true
      - product: pip
        component: pip-account-management
        ssl_enabled: true
