---

gateways:
  - gateway_configuration:
      host_name_suffix: staging.platform.hmcts.net
      ssl_host_name_suffix: staging.platform.hmcts.net
      certificate_name: wildcard-staging-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.148.32.138
    app_configuration:
    # Toffee
      - product: toffee
        component: recipe-backend
    # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
    # Publication and Information
      - product: pip
        component: business-rules
        ssl_enabled: true
      - product: pip
        component: publication-services
        ssl_enabled: true
      - product: pip
        component: data-management
        ssl_enabled: true
      - product: pip
        component: channel-management
        ssl_enabled: true
      - product: pip
        component: subscription-management
        ssl_enabled: true
      - product: pip
        component: account-management
        ssl_enabled: true
      # DTS Legacy Apps
      - product: lgy-iac
        component: web
        ssl_enabled: true
      # Darts Modernisation
      - product: darts
        component: api
        ssl_enabled: true
      - product: darts
        component: gateway
        ssl_enabled: false
      - product: darts
        component: stub-services
        ssl_enabled: false
     # Pre-Recorded Evidence
      - product: pre
        component: portal
        ssl_enabled: true
      - product: pre
        component: api
        ssl_enabled: true
     # Juror
      - product: juror
        component: scheduler-api
        ssl_enabled: true
      - product: juror
        component: scheduler-execution
        ssl_enabled: true
      - product: juror
        component: pnc
        ssl_enabled: true
      - product: juror
        component: api
        ssl_enabled: true
        health_path_override: /health
     # Opal
      - product: opal
        component: fines-service
        ssl_enabled: true
      - product: opal
        component: legacy-db-stub
        ssl_enabled: true
      - product: opal
        component: print-service
        ssl_enabled: true
      - product: opal
        component: log-audit-service
        ssl_enabled: true
     # PDDA
      - product: pdda
        component: public-display-data-aggregator.yaml
        ssl_enabled: true
