---

gateways:
  - gateway_configuration:
      host_name_suffix: demo.platform.hmcts.net
      ssl_host_name_suffix: demo.platform.hmcts.net
      certificate_name: wildcard-demo-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.51.32.121
    app_configuration:
    # PIP application
      - product: pip
        component: business-rules
        ssl_enabled: true
      - product: pip
        component: publication-services
        ssl_enabled: true
      - product: pip
        component: data-management
        ssl_enabled: true
      - product: pip
        component: channel-management
        ssl_enabled: true
      - product: pip
        component: subscription-management
        ssl_enabled: true
      - product: pip
        component: account-management
        ssl_enabled: true
