---

gateways:
  - gateway_configuration:
      host_name_suffix: demo.platform.hmcts.net
      ssl_host_name_suffix: demo.platform.hmcts.net
      certificate_name: wildcard-demo-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.51.96.132
    app_configuration:
      - product: dummy
        component: app
      - product: toffee
        component: recipe-backend

      # PIP
      - product: pip
        component: account-management
      - product: pip
        component: channel-management
      - product: pip
        component: data-management
      - product: pip
        component: publication-services
      - product: pip
        component: subscription-management
      
      # VH
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true

      # My-Time
      - product: my-time
        component: api
        
      # Darts Modernisation
      - product: darts
        component: darts-api
        ssl_enabled: true
      - product: darts
        component: darts-gateway
        ssl_enabled: true

