---

gateways:
  - gateway_configuration:
      host_name_suffix: demo.platform.hmcts.net
      ssl_host_name_suffix: demo.platform.hmcts.net
      certificate_name: wildcard-demo-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.51.96.132
    app_configuration:
      - product: dummy
        component: app
      - product: toffee
        component: recipe-backend

      # PIP
      - product: pip
        component: account-management
        ssl_enabled: true
      - product: pip
        component: channel-management
        ssl_enabled: true
      - product: pip
        component: data-management
        ssl_enabled: true
      - product: pip
        component: publication-services
        ssl_enabled: true
      - product: pip
        component: subscription-management
        ssl_enabled: true
      
      # VH
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true

      # My-Time
      - product: my-time
        component: api
        
      # Darts Modernisation
      - product: darts
        component: api
        ssl_enabled: true
      - product: darts
        component: gateway
        ssl_enabled: true
      - product: darts
        component: stub-services
        ssl_enabled: true

     # Pre-Recorded Evidence
      - product: pre
        component: portal
        ssl_enabled: true
      - product: pre
        component: api
        ssl_enabled: true

     # Juror
      - product: juror
        component: scheduler-api
        ssl_enabled: true
      - product: juror
        component: scheduler-execution
        ssl_enabled: true
      - product: juror
        component: pnc
        ssl_enabled: true
