---

gateways:
  - gateway_configuration:
      host_name_suffix: platform.hmcts.net
      ssl_host_name_suffix: platform.hmcts.net
      certificate_name: wildcard-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.11.8.200
    app_configuration:
      - product: sds
        component: api-mgmt-appgw
        ssl_enabled: true
        use_public_ip: true
        health_path_override: "/status-0123456789abcdef"
      - product: sds-mtls
        component: api-mgmt-appgw
        ssl_enabled: true
        use_public_ip: true
        health_path_override: "/status-0123456789abcdef"
        add_ssl_profile: true
        verify_client_cert_issuer_dn: true
