---

gateways:
  - gateway_configuration:
      host_name_suffix: platform.hmcts.net
      ssl_host_name_suffix: platform.hmcts.net
      certificate_name: wildcard-platform-hmcts-net
    app_configuration:
  # Toffee  
      - product: toffee
        component: backend
