---

gateways:
  - gateway_configuration:
      host_name_suffix: platform.hmcts.net
      ssl_host_name_suffix: platform.hmcts.net
      certificate_name: wildcard-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.144.32.136
    app_configuration:
  # Toffee
      - product: toffee
        component: backend
