---

gateways:
  - gateway_configuration:
      # host_name_suffix:
      # ssl_host_name_suffix:
      # certificate_name: 
    app_configuration:
    # Toffee
      # - product: toffee
      #   component: backend