---

gateways:
  - gateway_configuration:
      host_name_suffix: platform.hmcts.net
      ssl_host_name_suffix: platform.hmcts.net
      certificate_name: wildcard-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.144.32.136
    app_configuration:
  # Toffee
      - product: toffee
        component: backend
        priority: 10
    # Publication and Information
      - product: pip
        component: business-rules
        ssl_enabled: true
        priority: 20
      - product: pip
        component: publication-services
        ssl_enabled: true
        priority: 30
      - product: pip
        component: data-management
        ssl_enabled: true
        priority: 40
      - product: pip
        component: channel-management
        ssl_enabled: true
        priority: 50
      - product: pip
        component: subscription-management
        ssl_enabled: true
        priority: 60
      - product: pip
        component: account-management
        ssl_enabled: true
        priority: 70
    # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
        priority: 80
      - product: vh
        component: video-api
        ssl_enabled: true
        priority: 90
      - product: vh
        component: test-api
        ssl_enabled: true
        priority: 100
      - product: vh
        component: scheduler-jobs
        ssl_enabled: true
        priority: 110
      - product: vh
        component: notification-api
        ssl_enabled: true
        priority: 120
      - product: vh
        component: bookings-api
        ssl_enabled: true
        priority: 130
      - product: vh
        component: booking-queue-subscriber
        ssl_enabled: true
        priority: 140
