---
gateways:
  - gateway_configuration:
      host_name_suffix: platform.hmcts.net
      ssl_host_name_suffix: platform.hmcts.net
      certificate_name: wildcard-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.144.32.136
    app_configuration:
      # Toffee
      - product: toffee
        component: recipe-backend
      # Publication and Information
      - product: pip
        component: business-rules
        ssl_enabled: true
      - product: pip
        component: publication-services
        ssl_enabled: true
      - product: pip
        component: data-management
        ssl_enabled: true
      - product: pip
        component: account-management
        ssl_enabled: true
      # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
      # Darts Modernisation
      - product: darts
        component: api
        ssl_enabled: true
      - product: darts
        component: gateway
        ssl_enabled: false
      - product: darts
        component: proxy
        ssl_enabled: false
      # Libra GoB Integration Service
      - product: gob
        component: gateway
        host_name_prefix: cloudgobgateway
        ssl_enabled: true
        health_path_override: "/services/themisgatewayapi?wsdl"
        request_timeout: 120
     # Pre-Recorded Evidence
      - product: pre
        component: portal
        ssl_enabled: true
      - product: pre
        component: api
        ssl_enabled: true
     # Juror
      - product: juror
        component: scheduler-api
        ssl_enabled: true
      - product: juror
        component: scheduler-execution
        ssl_enabled: true
      - product: juror
        component: pnc
        ssl_enabled: true
      - product: juror
        component: api
        ssl_enabled: true
        health_path_override: /health
