---

gateways:
  - gateway_configuration:
      host_name_suffix: sandbox.platform.hmcts.net
      ssl_host_name_suffix: sandbox.platform.hmcts.net
      certificate_name: wildcard-sandbox-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.10.200.222
    app_configuration:
      - product: sds
        component: api-mgmt-appgw
        ssl_enabled: true
        use_public_ip: true
        health_path_override: "/status-0123456789abcdef"
      - product: sds-mtls
        component: api-mgmt-appgw
        ssl_enabled: true
        use_public_ip: true
        health_path_override: "/status-0123456789abcdef"
        add_ssl_profile: true
        verify_client_cert_issuer_dn: true
        certificate_name: lets_encrypt
      - product: sds-thomas
        component: thomas-appgw
        ssl_enabled: true
        use_public_ip: true
        health_path_override: "/status-0123456789abcdef"
        add_ssl_profile: true
        verify_client_cert_issuer_dn: true
        certificate_name: civil-sdt-root-ca

