---

gateways:
  - gateway_configuration:
      host_name_suffix: sandbox.platform.hmcts.net
      ssl_host_name_suffix: sandbox.platform.hmcts.net
      certificate_name: STAR-sandbox-platform-hmcts-net
    app_configuration:
    # Toffee
      - product: toffee
        component: backend
    # VH
      - product: vh
        component: user-api
        ssl_enabled: true