---

gateways:
  - gateway_configuration:
      host_name_suffix: sandbox.platform.hmcts.net
      ssl_host_name_suffix: sandbox.platform.hmcts.net
      certificate_name: wildcard-sandbox-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.140.32.134
    app_configuration:
    # Toffee
      - product: toffee
        component: recipe-backend
        priority: 10
    # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
        priority: 20
      - product: vh
        component: video-api
        ssl_enabled: true
        priority: 30
      - product: vh
        component: test-api
        ssl_enabled: true
        priority: 40
      - product: vh
        component: scheduler-jobs
        ssl_enabled: true
        priority: 50
      - product: vh
        component: notification-api
        ssl_enabled: true
        priority: 60
      - product: vh
        component: bookings-api
        ssl_enabled: true
        priority: 70
      - product: vh
        component: booking-queue-subscriber
        ssl_enabled: true
        priority: 80
    #labs
      - product: labs
        component: mokainos
        priority: 90
    # test
      - product: test
        component: override
        host_name_suffix_override: service.core-compute-sandbox.internal
        priority: 100