---

gateways:
  - gateway_configuration:
      host_name_suffix: sandbox.platform.hmcts.net
      ssl_host_name_suffix: sandbox.platform.hmcts.net
      certificate_name: STAR-sandbox-platform-hmcts-net
    app_configuration:
    # Toffee
      - product: toffee
        component: backend
    # VH
    # VH
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-web
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: service-web
        ssl_enabled: true
      - product: vh
        component: scheduler-jobs
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: booking-queue-subscriber
        ssl_enabled: true
      - product: vh
        component: admin-web
        ssl_enabled: true
      - product: vh
        component: test-web
        ssl_enabled: true
    # test
      - product: test
        component: override
        host_name_suffix_override: service.core-compute-sandbox.internal