---

gateways:
  - gateway_configuration:
      host_name_suffix: sandbox.platform.hmcts.net
      ssl_host_name_suffix: sandbox.platform.hmcts.net
      certificate_name: wildcard-sandbox-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.140.32.134
    app_configuration:
    # Toffee
      - product: toffee
        component: recipe-backend
    # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
    #labs
      - product: labs
        component: mokainos
    # test
      - product: test
        component: override
        host_name_suffix_override: service.core-compute-sandbox.internal