---

gateways:
  - gateway_configuration:
      host_name_suffix: service.core-compute-sandbox.internal
      ssl_host_name_suffix: sandbox.platform.hmcts.net
      certificate_name: STAR-sandbox-platform-hmcts-net
    app_configuration:
    # Toffee
      - product: toffee
        component: backend