---

gateways:
  - gateway_configuration:
      host_name_suffix: ithc.platform.hmcts.net
      ssl_host_name_suffix: ithc.platform.hmcts.net
      certificate_name: wildcard-ithc-platform-hmcts-net
    app_configuration:
    # Toffee
      - product: toffee
        component: backend
    # VH
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-web
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: service-web
        ssl_enabled: true
      - product: vh
        component: scheduler-jobs
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: booking-queue-subscriber
        ssl_enabled: true
      - product: vh
        component: admin-web
        ssl_enabled: true
      - product: vh
        component: test-web
        ssl_enabled: true