---

gateways:
  - gateway_configuration:
      host_name_suffix: ithc.platform.hmcts.net
      ssl_host_name_suffix: ithc.platform.hmcts.net
      certificate_name: wildcard-ithc-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.143.32.136
    app_configuration:
    # Toffee
      - product: toffee
        component: recipe-backend
    # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: admin-web
        ssl_enabled: true
      - product: vh
        component: video-web
        ssl_enabled: true
      - product: vh
        component: service-web
        ssl_enabled: true
      - product: vh
        component: test-web
        ssl_enabled: true
      # Darts Modernisation
      - product: darts
        component: api
        ssl_enabled: true
      - product: darts
        component: gateway
        ssl_enabled: true
      - product: darts
        component: stub-services
        ssl_enabled: true
    # Juror
      - product: juror
        component: scheduler-api
        ssl_enabled: true
      - product: juror
        component: scheduler-execution
        ssl_enabled: true
      - product: juror
        component: pnc
        ssl_enabled: true
