---

gateways:
  - gateway_configuration:
      host_name_suffix: ithc.platform.hmcts.net
      ssl_host_name_suffix: ithc.platform.hmcts.net
      certificate_name: wildcard-test-platform-hmcts-net
    app_configuration:
    # Toffee
      - product: toffee
        component: backend