---

gateways:
  - gateway_configuration:
      host_name_suffix: dev.platform.hmcts.net
      ssl_host_name_suffix: dev.platform.hmcts.net
      certificate_name: wildcard-dev-platform-hmcts-net
      exclude_env_in_app_name: true
    app_configuration:
    # Toffee application
      - product: toffee
        component: recipe-backend
    # Video Hearings
      - product: vh
        component: user-api
        ssl_enabled: true
      - product: vh
        component: video-web
        ssl_enabled: true
      - product: vh
        component: video-api
        ssl_enabled: true
      - product: vh
        component: test-api
        ssl_enabled: true
      - product: vh
        component: service-web
        ssl_enabled: true
      - product: vh
        component: scheduler-jobs
        ssl_enabled: true
      - product: vh
        component: notification-api
        ssl_enabled: true
      - product: vh
        component: bookings-api
        ssl_enabled: true
      - product: vh
        component: booking-queue-subscriber
        ssl_enabled: true
      - product: vh
        component: admin-web
        ssl_enabled: true
      - product: vh
        component: test-web
        ssl_enabled: true