---

gateways:
  - gateway_configuration:
      host_name_suffix: dev.platform.hmcts.net
      ssl_host_name_suffix: dev.platform.hmcts.net
      certificate_name: wildcard-dev-platform-hmcts-net
      exclude_env_in_app_name: true
      private_ip_address: 10.145.32.135
    app_configuration:
    # Toffee application
      - product: toffee
        component: recipe-backend
      # DTS Legacy Apps
      - product: lgy-iac
        component: web
        ssl_enabled: true
      # Darts Modernisation
      - product: darts
        component: api
        ssl_enabled: true
      - product: darts
        component: gateway
        ssl_enabled: false
      - product: darts
        component: stub-services
        ssl_enabled: false
     # Pre-Recorded Evidence
      - product: pre
        component: portal
        ssl_enabled: true
      - product: pre
        component: api
        ssl_enabled: true